### ISSUE TITLE
Reference and citation question

### ISSUE THREAD

**Issue by hjhaobuaa** [LinStab2D/LinStab2D#1]
Thank you for your contribution on the open source code. Could you please provide any open literature which you've already published? maybe they are helpful for others to study your code.  I also wonder how to cite this code in our work. 
 
Thank you for your work from the bottom of my heart.

**Comment by eduardomartini** [comment]
Hi hjhaobuaa,

we have a paper describing the code current in print. We will add a reference to the readme file once it is out!

**Comment by eduardomartini** [comment]
Hi hjhaobuaa,

The paper describing the code has been published (see this [link](https://link.springer.com/article/10.1007/s00162-024-00706-0) ) . The citing information can now be found in the main README file.

Best,
Eduardo

**Comment by hjhaobuaa** [comment]
Thank you very much, your open-source code and paper help me a lot
